# Rust formatting configuration
# https://rust-lang.github.io/rustfmt/

edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Style
use_small_heuristics = "Default"
fn_call_width = 80
struct_lit_width = 18
enum_variant_width = 35
array_width = 80
chain_width = 80

# Formatting
newline_style = "Unix"
remove_nested_parens = true
use_field_init_shorthand = true
use_try_shorthand = true
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
comment_width = 80

# Match
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true

# Control flow
control_brace_style = "AlwaysSameLine"
