[package]
name = "uti-daemon"
version = "0.1.2"
edition = "2021"

[dependencies]
evdev = { version = "0.12", features = ["tokio"] }
zbus = "4"
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
env_logger = "0.11"
log = "0.4"
